In [74]:
import numpy as np

In [75]:
ls_sudoku = [[0,0,0,2,6,0,7,0,1],
             [6,8,0,0,7,0,0,9,0],
             [1,9,0,0,0,4,5,0,0],
             [8,2,0,1,0,0,0,4,0],
             [0,0,4,6,0,2,9,0,0],
             [0,5,0,0,0,3,0,2,8],
             [0,0,9,3,0,0,0,7,4],
             [0,4,0,0,5,0,0,3,6],
             [7,0,3,0,1,8,0,0,0]]

In [76]:
sudoku = np.array(ls_sudoku)

In [90]:
def isValid(number, row, column):
    global sudoku

    for j in range(9):
        if number == sudoku[row][j]:
            return False
    
    for i in range(9):
        if number == sudoku[i][column]:
            return False
            
    subgrids = [[0, 0, 0, 1, 1, 1, 2, 2 ,2],
                [0, 0, 0, 1, 1, 1, 2, 2 ,2],
                [0, 0, 0, 1, 1, 1, 2, 2 ,2],
                [3, 3, 3, 4, 4, 4, 5, 5, 5],
                [3, 3, 3, 4, 4, 4, 5, 5, 5],
                [3, 3, 3, 4, 4, 4, 5, 5, 5],
                [6, 6, 6, 7, 7, 7, 8, 8, 8],
                [6, 6, 6, 7, 7, 7, 8, 8, 8],
                [6, 6, 6, 7, 7, 7, 8, 8, 8]]
    
    i_am_at_subgrid = subgrids[row][column]

    if i_am_at_subgrid == 0:
        sudoku_subgrid = sudoku[0:3, 0:3]
    elif i_am_at_subgrid == 1:
        sudoku_subgrid = sudoku[0:3, 3:6]
    elif i_am_at_subgrid == 2:
        sudoku_subgrid = sudoku[0:3, 6:10]
    elif i_am_at_subgrid == 3:
        sudoku_subgrid = sudoku[3:6, 0:3]
    elif i_am_at_subgrid == 4:
        sudoku_subgrid = sudoku[3:6, 3:6]
    elif i_am_at_subgrid == 5:
        sudoku_subgrid = sudoku[3:6, 6:10]
    elif i_am_at_subgrid == 6:
        sudoku_subgrid = sudoku[6:10, 0:3]
    elif i_am_at_subgrid == 7:
        sudoku_subgrid = sudoku[6:10, 3:6]
    elif i_am_at_subgrid == 8:
        sudoku_subgrid = sudoku[6:10, 6:10]

    if number in sudoku_subgrid:
        return False
    
    return True

In [93]:
def Solve():
    global sudoku

    #Recursion 
    for column in range(9):
        for row in range(9):
            if sudoku[row][column] == 0:
                for candidate in range(1, 10):
                    if isValid(candidate, row, column):
                        sudoku[row][column] = candidate
                        Solve()
                        sudoku[row][column] = 0
                return

    print(sudoku)
    input("More?")

In [94]:
Solve()

[[4 3 5 2 6 9 7 8 1]
 [6 8 2 5 7 1 4 9 3]
 [1 9 7 8 3 4 5 6 2]
 [8 2 6 1 9 5 3 4 7]
 [3 7 4 6 8 2 9 1 5]
 [9 5 1 7 4 3 6 2 8]
 [5 1 9 3 2 6 8 7 4]
 [2 4 8 9 5 7 1 3 6]
 [7 6 3 4 1 8 2 5 9]]
